arcalot/arcaflow-plugin-sdk-python

src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_schema.py
This PR adds a method that checks parent classes (recursively) for annotations.
I designed it with infinite recursion protection, a useful error message in the event of infinite recursion that specifies the class that was in the schema, and it preserves the annotations from the most-child class.
If any test cases need to be added for this, let me know. The 33 test cases for test_schema.py passed.
---
=> Support annotations from parent classes. Closes #43

.github/workflows/build.yml, docs/conf.py, src/arcaflow_plugin_sdk/plugin.py, src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_schema.py, test_example_plugin.py
Fixed issues reported by pyflakes and added automation for running pyflakes.
Fixes #64
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
---
=> pyflakes: fix issues and setup automation

.github/workflows/build.yml
avoid to get 3 coverage reports in job summary.
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
---
=> automation: add coverage to summary only once

src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_schema.py
Fixes #73 
First, I allow detection of the any type in the switch. It does not interfere with the non-any type checks.
Second, I added NoneType to the list of allowed values, because None values in maps and lists are important in a lot of situations, including my metadata plugin
Lastly, I added more test cases for AnyType.
---
=> Fixed any type output, and added None to list of allowed types

src/arcaflow_plugin_sdk/plugin.py
I've found the steps parts of the CLI quite unhelpful. In this step I add step help by printing out the names of the steps, and I added the missing schema output to the main help message.
---
=> Improved CLI help messages

.flake8, .github/workflows/build.yml, .pre-commit-config.yaml, docs/conf.py, example_plugin.py, poetry.lock, pyproject.toml, setup.cfg, src/arcaflow_plugin_sdk/_http.py, src/arcaflow_plugin_sdk/atp.py, src/arcaflow_plugin_sdk/jsonschema.py, src/arcaflow_plugin_sdk/plugin.py, src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/serialization.py, src/arcaflow_plugin_sdk/test_atp.py, src/arcaflow_plugin_sdk/test_jsonschema.py, src/arcaflow_plugin_sdk/test_plugin.py, src/arcaflow_plugin_sdk/test_schema.py, test_example_plugin.py
We add various pre-commit checks which double-check various aspects of the code.
We perform the auto-code changes from `black`, `isort`, and `flake8` in separate commits to help make it easier to verify all the changes.
---
=> Convert project to use poetry and pre-commit

src/arcaflow_plugin_sdk/atp.py
This is a very simple PR that adds an error check for a failure case that has happened in some plugins. This should just make it a bit easier to debug.
---
=> Added error message for null work start message

src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_schema.py
1. Fix bug that throws a `ConstraintException` when a plugin input dataclass attribute with a `required_if` property is not set
2. Fix similar bug for `required_if_not`
3. Add `required_if` test cases to cover unserialization, serialization, and validation
4.  Add `required_if_not` test cases to cover unserialization, serialization, and validation
---
=> Fix Required If (Not) Properties

src/arcaflow_plugin_sdk/schema.py
Small bug fix resolves #92. A `name` value was errantly being set instead of `description`
---
=> correct reference from name to description

.github/workflows/build.yml, src/arcaflow_plugin_sdk/atp.py, src/arcaflow_plugin_sdk/plugin.py, src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_atp.py, test_example_plugin.py
This update adds the changes that correspond to the go SDK ATP v3 update: https://github.com/arcalot/arcaflow-plugin-sdk-go/pull/57
The error reporting in this version is **massively** improved. Now errors in the ATP and the plugin are properly reported to the ATP client, which is then reported by the engine.
Some of the suggestions by Webb were also addressed in this branch.
---
=> ATP v3 update

poetry.lock, pyproject.toml, src/arcaflow_plugin_sdk/atp.py, src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_atp.py
This PR updates to cbor2, which is annoyingly a breaking change for a minor version.
It also addresses the comments that Webb left on my prior PR.
I have not tested this with plugins, but the tests pass, and **theoretically** I fixed things and didn't break anything. 😄 
---
=> Updated to cbor2 5.5.0, and addressed review comments

.github/workflows/build.yml, example_plugin.py, poetry.lock, pyproject.toml, src/arcaflow_plugin_sdk/atp.py, src/arcaflow_plugin_sdk/jsonschema.py, src/arcaflow_plugin_sdk/plugin.py, src/arcaflow_plugin_sdk/predefined_schemas.py, src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/serialization.py, src/arcaflow_plugin_sdk/test_atp.py, src/arcaflow_plugin_sdk/test_jsonschema.py, src/arcaflow_plugin_sdk/test_plugin.py, src/arcaflow_plugin_sdk/test_schema.py, test_example_plugin.py
Almost no style checks nor linting was performed on this repository until now, so this is a big one.
---
=> Fix and Apply CI Lint Checks

src/arcaflow_plugin_sdk/test_schema.py
In anticipation of adding the `discriminator_inlined` attribute to OneOf's, this pull request refactors the minimum code in `OneOfTest` that is expected to be reused across the new unit tests in the anticipated pull request. There are still some remaining spots where code could be deduplicated, but I only wanted to dry out the parts I was most confident that I would reuse.
---
=> Dry Out OneOf Test Suite

src/arcaflow_plugin_sdk/atp.py, src/arcaflow_plugin_sdk/test_atp.py
=> bug fix atp

src/arcaflow_plugin_sdk/test_schema.py
Factor out some basic dataclasses so they can be used across multiple Test Classes.
---
=> Oneof refactor 2

.github/workflows/build.yml
This PR fixes a breakage introduced in #120 in which the `publish` job in the CI workflow tries to reference the build artifact using one of the matrix values, but these are only valid in the `build` job.  This problem only occurs when building tagged commits, e.g., for releases.
This PR references `vars.ARCALOT_PYTHON_VERSION` instead, so that we have a single, consistent source of truth for the version of Python that we support.  This PR also changes direct references to `3.9` in the `build` workflow (e.g., in the matrix list and in the conditional around producing the coverage data) to use the variable, as well.  Also, this PR adds a conditional around uploading the coverage data, so that we do it only once.
---
By contributing to this repository, I agree to the [contribution …
=> Fix publish workflow

src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_plugin.py
This PR adds a check to make it more obvious to the plugin author what their mistake is.
---
=> Detect invalid step return

src/arcaflow_plugin_sdk/atp.py, src/arcaflow_plugin_sdk/plugin.py, src/arcaflow_plugin_sdk/test_atp.py
Some programs expect the buffer to be there. This ensures that it is.
---
=> Use a buffered stdout substitute

src/arcaflow_plugin_sdk/schema.py
For cross-compatibility this needs to be added from the Go SDK. It is not used in the Python SDK at the moment.
I'm not sure if I handled the defaults in the best way. Let me know if you have any feedback.
---
=> Add loose_id field.

src/arcaflow_plugin_sdk/schema.py, src/arcaflow_plugin_sdk/test_schema.py
All attributes on the *Schema classes, like `OneOfStringSchema` or `OneOfIntSchema`, in `schema.py` must be public because the schema builder portion of `schema.py` uses metadata analysis of that class's attributes to determine if an instance of the Arcaflow type has been written as specified by the Arcaflow type system (implemented by the *Schema classes and a few other parts of this code base). As a language feature of Python, classes do not have private/hidden attributes. If a private attribute must exist on a *Schema class, then one solution is to encapsulate the required behavior or state on a part of the class that is not used as a part of the metadata analysis. In this pull request I have encapsulated the state we would like to be hidden within method calls on the relevant classes. …
=> Hide OneOfSchema Attributes 
